worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    server_tokens off; # Seguridad: Ocultar versión de Nginx

    # Definición del clúster de backends
    upstream backend_servers {
        server apache1:80;
        server apache2:80;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend_servers;
            
            # Configuración de cabeceras de Proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Cabeceras para identificación de auditoría (Examen)
            proxy_pass_header X-Backend-Server;
            add_header X-LB-Node $upstream_addr always;
            
            # Timeout para mayor robustez
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
        }

        # Error pages
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
